spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**
  datasource:
    url: jdbc:mysql://localhost:3306/ebm?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: 'true'    
  mail:
        host: smtp.gmail.com
        password: '[your generated password]'
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: javadev.darshit@gmail.com  
